bib_all: Habsburg_sample_new.bib
bib_single: Habsburg_biblatex_single.bib
bib_top: Habsburg_biblatex_top.bib
memex_path: C:\Users\elias\OneDrive\Desktop\Eigene Dateien\Master\Kurse WiSe 2020\Methodenkurs DH\Classes\MEMEX_SANDBOX\data